<?php

return [
    'layouts.nav.profil' => 15,
    "layouts.nav.logout"=>11,
    "layouts.nav.greet"=>5,
    "layouts.nav.login"=>12,
    "layouts.nav.open"=>15,
    "layouts.nav.home"=>7,
    "layouts.nav.about"=>8,
    "layouts.nav.opportunities"=>12,
    "layouts.nav.install"=>10,
    "layouts.nav.partners"=>14,
    "layouts.nav.galery"=>7,
    "layouts.nav.media"=>10,
    "layouts.nav.news"=>7,
    "layouts.nav.register"=>9,
    "layouts.footer.address" =>23,
    "layouts.footer.phone"=>26,
    "layouts.footer.email"=>15,
    "layouts.footer.country"=>13,
    "layouts.footer.join_us"=>14,
    "layouts.footer.menu"=>5,
    "layouts.footer.job"=>14,
    "layouts.footer.tender"=>13,
    "layouts.footer.quotation"=>24,
    "layouts.footer.event"=>20,
    "layouts.footer.career"=>9,
    "layouts.footer.newsletter"=>9,
    "layouts.footer.newsletter.description"=>69,
    "layouts.footer.follow"=>8,
    "layouts.footer.facebook"=>13,
    "layouts.footer.twitter"=>12,
    "layouts.footer.youtube"=>11,
    "layouts.footer.linkedin"=>9,
    "layouts.footer.copyright"=>68,
    "profil.layouts.requests.index"=>17,
    "profil.layouts.requests.follow"=>18,
    "profil.layouts.documents"=>16,
    "profil.layouts.requests.edit"=>23,
    "profil.layouts.requests.new"=>16,
    "profil.layouts.requests.message"=>8,
    "profil.layouts.requests.welcome"=>9,
    "profil.layouts.requests.profile"=>6,
    "home.at"=>2,
    "home.technological_park_of_ivory_coast"=>38,
    "home.fiscal_and_regulatory_advantages"=>35,
    "home.customs_advantages"=>19,
    "home.partneships"=>25,
    "home.access_to_a_thriving_market"=>31,
    "home.government_support"=>24,
    "home.innovation_environment"=>26,
    "home.skilled_workforce"=>27,
    "home.state_of_the_art_infrastructure"=>26,
    "home.innovate_in_the_heart_of_africa"=>30,
    "home.welcome_to_vitib"=>93,
    "home.excellence_in_innovation_and_technological_development"=>92,
    "home.located_in_the_heart_of_africa"=>78,
    "home.vitib_is_a_technology_free_zone"=>68,
    "home.read_more"=>9,
    "home.tech_space_for_you"=>25,
    "home.proud_to_offer_dynamic_ecosystem"=>316,
    "home.smart_city"=>10,
    "home.zbtic_is_a_territory_with_favorable_tax_policies"=>454,
    "about.vision"=>56,
    "about.director_general_message_title"=>24,
    "about.director_general_message"=>1460,
    "about.director_general_name"=>15,
    "about.director_general"=>26,
    "about.mission.title"=>8,
    "about.mission.describe"=>288,
    "about.mission.content"=>839,
    "about.value.title"=>8,
    "about.value.content"=>742,
    "opportunity.title"=>15,
    "opportunity.administration_zone"=>18,
    "opportunity.production_zone_assembly_industries"=>34 ,
    "opportunity.production_zone_biotechnology_industries"=>36 ,
    "opportunity.production_zone_offices"=>29 ,
    "opportunity.future_development"=>17,
    "opportunity.logistics_zone"=>15,
    "opportunity.residential_zone"=>16,
    "opportunity.bus_station"=>11,
    "opportunity.green_zone"=>10,
    "opportunity.utility"=>7,
    "opportunity.future_projects_title"=>15,
    "opportunity.future_projects_warehouses_for_rent"=>17,
    "opportunity.future_projects_warehouses_description"=>180,
    // "opportunity.promotion_block_a_title":"<h5>Promotion Immobilière Bloc A</h5>",
    // "opportunity.promotion_block_a_description":"<p>Cette promotion immobilière doit prendre en compte un compte un programme spécifique d’habitants réalisées à titre gracieux pour VITIB S.A. Le reste de la parcelle (80%) pourra être commercialisé. 2 Ce projet doit inclure à la fois des habitations collectives de moyen et haut standing (appartements) et des habitations pavillonnaires (villas).</p>",
    // "opportunity.future_projects.office_buildings":"<h5>Immeubles à bureaux</h5>",
    // "opportunity.future_projects.office_buildings_description":"<p>Cette zone inclut une zone économique TIC-soft, ayant pour objet l’hébergement des entreprises œuvrant dans le secteur des TIC. Les infrastructures d’accueil de ce type d’entreprises répond à des standards internationaux, en vue de répondre aux exigences des multinationales (Microsoft, Oracle, Apple, Google) attendues dans le parc technologique de la zone franche. Ce sont un total de plus de 20 000 employés qui sont attendus dans la zone.</p>",
    // "opportunity.business_hotels_title":"<h5 >Hôtels d’affaires</h5>",
    // "opportunity.business_hotels_description":"<p>Voisin du futur centre des Congrès du parc technologique, cet hôtel d’affaires offrira une solution d’hébergement aux différents experts, cadres et visiteurs des sociétés en opération sur le site de la ZBTIC.</p>",
    // "opportunity.university_title":"<h5>Université</h5>",
    // "opportunity.university_description":"<p>Le Village de l’Innovation Technologique a pour vocation d’être le centre de la réflexion technologique en Afrique de l’Ouest. La création d’un établissement académique de niveau universitaire permettra de former les scientifiques et les managers de demain. L’établissement tirera avantage de la proximité des entreprises installées au sein de la zone économique spéciale.</p>",
    // "opportunity.international_medical_clinic_title":"<h5>Clinique médicale internationale</h5>",
    // "opportunity.international_medical_clinic_description":"<p>Une clinique médicale de stature internationale correspondant aux standards internationaux, vise à offrir à minima des services de médecine générale et des services spécialisés à la clientèle et aux travailleurs de la ZBTIC.</p>",
    // "opportunity.cultural_center_title":"<h5>Centre Culturel</h5>",
    // "opportunity.promotion_block_b_title":"<h5>Promotion Immobilier Bloc B</h5>",
    // "opportunity_section_title":"<h1>Projets & Services</h1>",
    // "opportunity_section_subtitle":"<p >Investissez sur ses opportunités dans un lieu unique</p>",
    // "opportunity_office_buildings":"<p>Immeubles à<br>bureaux</p>",
    // "opportunity_university":"<p>Université</p>",
    // "opportunity_warehouses_for_rent":"<p>Entrepôts à<br>louer</p>",
    // "opportunity_international_medical_clinic":"<p>Clinique Médicale<br>Internationale</p>",
    // "opportunity_commercial_alley":"<p >Allée<br>Commerciale</p>",
    // "opportunity_cultural_center":"<p>Centre<br>Culturel</p>",
    // "installer.title":"<h1>COMMENT S'INPLANTER</h1>",
    // "installer.eligibility_prerequisites_title":" <h1> Eligibilité – Pré-requis</h1>",
    // "installer.eligibility_prerequisites_subtitle":"<p>Le bénéfice du régime de la ZBTIC est soumis à l’obtention d’un agrément délivré par l’EPE (VITIB S.A). Pour ce faire, les sociétés désireuses de s’implanter sur la zone franche en qualité d’Entreprises Utilisatrices doivent opérer dans les domaines d’activités suivants :</p>",
    // "installer.eligibility_prerequisites_biotechnology":" <p>Biotechnologie</p>",
    // "installer.eligibility_prerequisites_information":" <p> Technologies de l’Information et de la Communication</p>",
    // "installer.eligibility_prerequisites_banks":"<p>  Banques et Établissements financiers d’appui aux investissements réalisés dans la Zone Franche.</p>",
    // "installer.eligibility_prerequisites_vitib":"<p>VITIB offre également des opportunités d’investissements dans l’immobilier en BOO et BOT sur 180 Ha en aménagement, avec en vue la création d’une nouvelle ville. VITIB recherche des partenaires techniques et financiers en mode PPP pour le financement et la réalisation de projets urbains sur la Zone Franche de Grand-Bassam. Par ailleurs, une zone résidentielle et commerciale de 62 Ha est réservée pour offrir des solutions de logements de proximité à près de 20000 employés de la ZBTIC.</p>",
    // "installer.approval_procedure":"<h1> Procédure d'agrément<h1>",
    // "installer.eligible_activities_title":"<h1> ACTIVITES ELLIGIBLES</h1>",
    // "installer.eligible_activities_industrial":"  <p>Activités Industrielles</p>",
    // "installer.eligible_activities_research_development":" <p>Recherche et développement</p>",
    // "installer.eligible_activities_research_development_title":" <h1>Recherche et développement</>",
    // "installer.eligible_activities_accompanying":" <p>  Activités d'accompagnement</p>",
    // "installer.eligible_activities_capacity building":"<p>Renforcement des capacités</p>",
    // "installer.eligible_activities_services":"<p>Services à valeur ajoutée</p>",
    // "installer.industrial_activities_title":"<h1> Activités industrielles </h1>",
    // "installer.industrial_activities_computer":"<p> Conception, fabrication et assemblage <br> de produits informatiques</p>",
    // "installer.industrial_telecom":"<p>Conception, fabrication et assemblage <br> de produits télécoms et réseaux</p>",
    // "installer.industrial_biotechnology":"<p>Conception, fabrication et assemblage <br> d'instruments de test et de recherche <br> biotechnologie</p>",
    // "installer.industrial_biotechnology products":"<p>Fabrication de produits biotechnologies<br>divers (médecine, pharmacie, agroalimentaire,<br>énergie, environnement, industrie, mines )</p>",
    // "installer.industrial_audiovisual":"<p> Production de contenus audiovisuels</p>",
    // "installer.industrial_software":"<p>Edition de logiciels et progiciels</p>",
    // "installer.capacity_building":" <h1> Renforcement des capacités </h1>",
    // "installer.value-added_title":" <h1> Services à valeur ajoutée </h1>",
    // "installer.value-added_content":" <p>Les services à valeur ajoutée sont des services dans le cadre desquels les fournisseurs ajoutent une valeur<br>aux informations fournies par le client en améliorant leur forme ou leur contenu ou en prévoyant leur stockage et leur recherche.</p>",
    // "installer.activities_accompanying_title":"<h1>Activités d'accompagnement</h1>",
    // "installer.activities_accompanying_content":"<p>Outre ces activités privilégiées, la ZBTIC accueille un ensemble de services d'accompagnement :</p>",
    // "installer.join_us_title":"<h1>COMMENT NOUS REJOINDRE</h1>",
    // "installer.join_us_subtitle":"<h2>TÉLÉCHARGER LE DOSSIER DE DEMANDE D’AGRÉMENT</h2>",
    // "installer.join_us_content":" <p>Une opportunité exceptionnelle au VITIB. Bénéficiez d'avantages fiscaux, d'une infrastructure de pointe et d'un écosystème dynamique propice à l'innovation. Immergez votre entreprise dans un environnement stratégique et prospère, prêt à accueillir les entreprises technologiques les plus prometteuses.</p>",
    // "installer.join_us_vision":"<p>Rejoignez-nous dès aujourd'hui et transformez l'avenir de votre entreprise au cœur de l'Afrique.</p>",
    // "installer.form_vitib":"<p>Formulaire de demande d’agrément VITIB</p>",
    // "installer.opportunity_list":" <p> Consulter la liste des opportunités d’investissement (investir au VITIB)</p>",
    // "installer.form_pepiniere":" <p>Formulaire de demande d'agrément Pépinière</p>",
];
